/**
 * @enum {string}
 */
const Citizenship = {
  Apolide: "Nessuno",
  Afghana: "Afghanistan",
  Albanese: "Albania",
  Algerina: "Algeria",
  Andorrana: "Andorra",
  Angolana: "Angola",
  Antiguana: "Antigua e Barbuda",
  Saudita: "Arabia Saudita",
  Argentina: "Argentina",
  Armena: "Armenia",
  Australiana: "Australia",
  Austriaca: "Austria",
  Azera: "Azerbaigian",

  Bahamense: "Bahamas",
  Bahreinita: "Bahrein",
  Bangladese: "Bangladesh",
  Barbadiana: "Barbados",
  Belga: "Belgio",
  Beliziana: "Belize",
  Beninese: "Benin",
  Bhutanese: "Bhutan",
  Bielorussa: "Bielorussia",
  Boliviana: "Bolivia",
  Bosniaca: "Bosnia ed Erzegovina",
  Botswanese: "Botswana",
  Brasiliana: "Brasile",
  Bruneiana: "Brunei",
  Bulgara: "Bulgaria",
  Burkinabé: "Burkina Faso",
  Burundese: "Burundi",

  Cambogiana: "Cambogia",
  Camerunense: "Camerun",
  Canadese: "Canada",
  Capoverdiana: "Capo Verde",
  Ciadiana: "Ciad",
  Cilena: "Cile",
  Cinese: "Cina",
  Cipriota: "Cipro",
  Colombiana: "Colombia",
  Comoriana: "Comore",
  Congolese: "Congo",
  Nordcoreana: "Corea del Nord",
  Sudcoreana: "Corea del Sud",
  Costaricana: "Costa Rica",
  Ivoriana: "Costa d’Avorio",
  Croata: "Croazia",
  Cubana: "Cuba",

  Danese: "Danimarca",
  Dominicana: "Dominica",
  Dominicana_RD: "Repubblica Dominicana",

  Ecuadoriana: "Ecuador",
  Egiziana: "Egitto",
  Salvadoregna: "El Salvador",
  Emiratina: "Emirati Arabi Uniti",
  Eritrea: "Eritrea",
  Estone: "Estonia",
  Swatina: "Eswatini",
  Etiope: "Etiopia",

  Figiana: "Figi",
  Filippina: "Filippine",
  Finlandese: "Finlandia",
  Francese: "Francia",

  Gabonese: "Gabon",
  Gambiana: "Gambia",
  Georgiana: "Georgia",
  Tedesca: "Germania",
  Ghanese: "Ghana",
  Giamaicana: "Giamaica",
  Giapponese: "Giappone",
  Gibutiana: "Gibuti",
  Giordana: "Giordania",
  Greca: "Grecia",
  Grenadina: "Grenada",
  Guatemalteca: "Guatemala",
  Guineana: "Guinea",
  Guineense: "Guinea-Bissau",
  Equatoguineana: "Guinea Equatoriale",
  Guyanese: "Guyana",

  Haitiana: "Haiti",
  Honduregna: "Honduras",
  Indiana: "India",
  Indonesiana: "Indonesia",
  Iraniana: "Iran",
  Irachena: "Iraq",
  Irlandese: "Irlanda",
  Islandese: "Islanda",
  Israeliana: "Israele",
  Italiana: "Italia",

  Kazaka: "Kazakistan",
  Kenyana: "Kenya",
  Kirghisa: "Kirghizistan",
  Kiribatiana: "Kiribati",
  Kosovara: "Kosovo",
  Kuwaitiana: "Kuwait",

  Laotiana: "Laos",
  Lesothiana: "Lesotho",
  Lettone: "Lettonia",
  Libanese: "Libano",
  Liberiana: "Liberia",
  Libica: "Libia",
  Liechtensteiniana: "Liechtenstein",
  Lituana: "Lituania",
  Lussemburghese: "Lussemburgo",

  Macedone: "Macedonia del Nord",
  Malgascia: "Madagascar",
  Malawiana: "Malawi",
  Malese: "Malaysia",
  Maldiviana: "Maldive",
  Maliana: "Mali",
  Maltese: "Malta",
  Marocchina: "Marocco",
  Marshallese: "Isole Marshall",
  Mauritana: "Mauritania",
  Mauriziana: "Mauritius",
  Messicana: "Messico",
  Micronesiana: "Micronesia",
  Moldava: "Moldavia",
  Monegasca: "Monaco",
  Mongola: "Mongolia",
  Montenegrina: "Montenegro",
  Mozambicana: "Mozambico",
  Birmana: "Myanmar",

  Namibiana: "Namibia",
  Nauruana: "Nauru",
  Nepalese: "Nepal",
  Nicaraguense: "Nicaragua",
  Nigerina: "Niger",
  Nigeriana: "Nigeria",
  Norvegese: "Norvegia",
  Neozelandese: "Nuova Zelanda",

  Omanita: "Oman",

  Pakistana: "Pakistan",
  Palauana: "Palau",
  Palestinese: "Palestina",
  Panamense: "Panama",
  Papua: "Papua Nuova Guinea",
  Paraguayana: "Paraguay",
  Olandese: "Paesi Bassi",
  Peruviana: "Perù",
  Polacca: "Polonia",
  Portoghese: "Portogallo",

  Qatarina: "Qatar",

  Britannica: "Regno Unito",
  Ceca: "Repubblica Ceca",
  Centrafricana: "Repubblica Centrafricana",
  Romena: "Romania",
  Ruandese: "Ruanda",
  Russa: "Russia",

  Nevisiana: "Saint Kitts e Nevis",
  Luciana: "Saint Lucia",
  Vincentina: "Saint Vincent e Grenadine",
  Samoana: "Samoa",
  Sammarinese: "San Marino",
  Santomese: "São Tomé e Príncipe",
  Senegalese: "Senegal",
  Serba: "Serbia",
  Seychellese: "Seychelles",
  Sierraleonese: "Sierra Leone",
  Singaporiana: "Singapore",
  Siriana: "Siria",
  Slovacca: "Slovacchia",
  Slovena: "Slovenia",
  Somala: "Somalia",
  Spagnola: "Spagna",
  Singalese: "Sri Lanka",
  Statunitense: "Stati Uniti",
  Sudafricana: "Sudafrica",
  Sudanese: "Sudan",
  Sudsudanese: "Sudan del Sud",
  Surinamese: "Suriname",
  Svedese: "Svezia",
  Svizzera: "Svizzera",

  Tagika: "Tagikistan",
  Thailandese: "Thailandia",
  Tanzaniana: "Tanzania",
  Timorese: "Timor Est",
  Togolese: "Togo",
  Tongana: "Tonga",
  Trinidadiana: "Trinidad e Tobago",
  Tunisina: "Tunisia",
  Turca: "Turchia",
  Turkmena: "Turkmenistan",
  Tuvaluana: "Tuvalu",

  Ucraina: "Ucraina",
  Ugandese: "Uganda",
  Ungherese: "Ungheria",
  Uruguaiana: "Uruguay",
  Uzbeka: "Uzbekistan",

  Vanuatiana: "Vanuatu",
  Vaticana: "Vaticano",
  Venezuelana: "Venezuela",
  Vietnamita: "Vietnam",

  Yemenita: "Yemen",

  Zambiana: "Zambia",
  Zimbabwese: "Zimbabwe"
};
